spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  address: 0.0.0.0
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000  # 30 phút
  refresh-expiration: 604800000  # 7 ngày