spring:
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    generate-ddl: true
    defer-datasource-initialization: true

  codec:
    max-in-memory-size: 52428800  # 50MB

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  rabbitmq:
    host: "${RABBITMQ_HOST}"
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
    virtual-host: "${RABBITMQ_VHOST}"
    ssl:
      enabled: true

r2:
  account-id: ${R2_ACCOUNT_ID}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket-name: ${R2_BUCKET_NAME}
  region: auto
  public-url: https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com/${R2_BUCKET_NAME}

storage:
  local:
    base-path: uploads

llama-parse:
  api-key: "${LLAMAPARSE_API_KEY}"

analysis:
  batch-size: 20

# GG Drive
google:
  drive:
    folder-id: ${FOLDER_ID}
    use-shared-drive: false
