spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: true
    connection-timeout: 30000
    requested-heartbeat: 60

  codec:
    max-in-memory-size: 52428800  # 50MB

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

gemini:
  api-key: ${GEMINI_API_KEY}