spring:
  config:
    import: optional:classpath:.env[.properties]

  rabbitmq:
    host: localhost
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

gemini:
  api-key: ${GEMINI_API_KEY}
