spring:
  application:
    name: ai-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

gemini:
  api-key: ${GEMINI_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  address: 0.0.0.0
  port: 8083
